### PR TITLE
Fix missing intsizeof import.

### PR DESCRIPTION
**Pull request by ned14**
Made a boo boo earlier, sorry.

### CODE REVIEW

**Comment by bazfp** [comment]
This is needed as current hunter release is breaking anything that uses CURL!

**Comment by ned14** [comment]
@rbsheth

**Comment by bazfp** [comment]
Does this need a `hunter_add_package` as well?

**Review by rbsheth — APPROVED** [review]

**Comment by rbsheth** [comment]
@ned14 Released: https://github.com/cpp-pm/curl/releases/tag/v7.74.0-p2

**Pull request merged**
